import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // English translations
        'en_US': {
          'select_language': 'Select Language',
          'onboarding_title1': 'Navigate Your World',
          'onboarding_subtitle1':
              'Get where you need to go with real-time directions and traffic updates. Enter your destination and start your journey.',
          'onboarding_title2': 'Reach New Heights',
          'onboarding_subtitle2':
              'Track your elevation on your next adventure. Perfect for hiking, biking, and more.',
          'onboarding_title3': 'Stay Ahead of the Weather',
          'onboarding_subtitle3':
              'Get the latest weather updates for your location. Plan your day with confidence.',
          'skip': 'Skip',
          'voice_gps_navigator': 'Voice GPS Navigator',
          'route_finder': 'Route Finder',
          'find_route_title': 'Find route to your destination.',
          'find_route': 'Find Route',
          'travel_essentials': 'Travel Essentials',
          'nearby_places': 'Nearby Places',
          'nearby_places_title': 'Explore Around You.',
          'speedometer': 'Speedometer',
          'speedometer_title': 'Gauge Your Speed.',
          'weather': 'Weather',
          'weather_title': 'Sun, Rain, Shine.',
          'navigation_tools': 'Navigation Tools',
          'altimeter': 'Altimeter',
          'altimeter_title': 'Measure Your \nAltitude.',
          'compass': 'Compass',
          'compass_title': 'Point to \nAdventure.',
          'my_location': 'My Location',
          'my_location_title': 'Find Your Way.',
          'street_view': 'Street View',
          'street_view_title': 'Explore the \nStreets.',
          'discovery_exploration': 'Discovery & Exploration',
          'famous_places': 'Famous Places',
          'famous_places_title': 'Famous Sites \nAwait.',
          'seven_wonders': 'Seven Wonders',
          'seven_wonders_title': 'Discover the \nWonders.',
          'settings': 'Settings',
          'general': 'General',
          'language': 'Language',
          'themes': 'Themes',
          'about': 'About',
          'privacy_policy': 'Privacy Policy',
          'rate_us': 'Rate Us',
          'share': 'Share',
          'airport': 'Airport',
          'aquarium': 'Aquarium',
          'art_gallery': 'Art Gallery',
          'atm': 'ATM',
          'automotive': 'Automotive',
          'bakery': 'Bakery',
          'bank': 'Bank',
          'bar': 'Bar',
          'bicycle_store': 'Bicycle Store',
          'book_store': 'Book Store',
          'bowling': 'Bowling',
          'bus_station': 'Bus Station',
          'cafeteria': 'Cafeteria',
          'car_wash': 'Car Wash',
          'cemetery': 'Cemetery',
          'church': 'Church',
          'city_hall': 'City Hall',
          'clothing_store': 'Clothing Store',
          'college_university': 'College University',
          'court_house': 'Court House',
          'dentist': 'Dentist',
          'doctor': 'Doctor',
          'department': 'Department',
          'electrician': 'Electrician',
          'electronic_store': 'Electronic Store',
          'embassy': 'Embassy',
          'furtniture_store': 'Furniture Store',
          'gas_station': 'Gas Station',
          'gym': 'Gym',
          'hardware_store': 'Hardware Store',
          'hospital': 'Hospital',
          'hotel': 'Hotel',
          'jewelry_store': 'Jewelry Store',
          'laundry': 'Laundry',
          'lawyer': 'Lawyer',
          'library': 'Library',
          'mosque': 'Mosque',
          'museum': 'Museum',
          'painter': 'Painter',
          'park': 'Park',
          'parking': 'Parking',
          'pharmacy': 'Pharmacy',
          'pet_store': 'Pet Store',
          'plumber': 'Plumber',
          'police_station': 'Police Station',
          'post_office': 'Post Office',
          'real_estate': 'Real Estate',
          'restaurant': 'Restaurant',
          'school': 'School',
          'shopping_mall': 'Shopping Mall',
          'spa': 'Spa',
          'stadium': 'Stadium',
          'subway_station': 'Subway Station',
          'taxi_stand': 'Taxi Stand',
          'travel_agency': 'Travel Agency',
          'zoo': 'Zoo',
        },
        // Arabic translations
        'ar_SA': {
          'select_language': 'اختر اللغة',
          'onboarding_title1': 'تصفح عالمك',
          'onboarding_subtitle1':
              'احصل على الاتجاهات وتحديثات حركة المرور في الوقت الحقيقي. أدخل وجهتك وابدأ رحلتك.',
          'onboarding_title2': 'وصل إلى ارتفاعات جديدة',
          'onboarding_subtitle2':
              'تتبع ارتفاعك في مغامرتك القادمة. مثالي للمشي لمسافات طويلة وركوب الدراجات وأكثر.',
          'onboarding_title3': 'ابقى على اطلاع بالطقس',
          'onboarding_subtitle3':
              'احصل على آخر تحديثات الطقس لموقعك. خطط ليومك بثقة.',
          'skip': 'تخطى',
          'voice_gps_navigator': 'ملاح الصوت GPS',
          'route_finder': 'العثور على الطريق',
          'find_route_title': 'العثور على الطريق إلى وجهتك.',
          'find_route': 'العثور على الطريق',
          'travel_essentials': 'ضروريات السفر',
          'nearby_places': 'الأماكن القريبة',
          'nearby_places_title': 'استكشف من حولك.',
          'speedometer': 'عداد السرعة',
          'speedometer_title': 'قياس سرعتك.',
          'weather': 'الطقس',
          'weather_title': 'شمس، مطر، لمعان.',
          'navigation_tools': 'أدوات الملاحة',
          'altimeter': 'مقياس الارتفاع',
          'altimeter_title': 'قياس ارتفاعك.',
          'compass': 'بوصلة',
          'compass_title': 'توجه إلى المغامرة.',
          'my_location': 'موقعي',
          'my_location_title': 'العثور على طريقك.',
          'street_view': 'عرض الشارع',
          'street_view_title': 'استكشف الشوارع.',
          'discovery_exploration': 'اكتشاف واستكشاف',
          'famous_places': 'أماكن مشهورة',
          'famous_places_title': 'المواقع الشهيرة تنتظر.',
          'seven_wonders': 'سبع عجائب',
          'seven_wonders_title': 'اكتشف العجائب.',
          'settings': 'الإعدادات',
          'general': 'عام',
          'language': 'لغة',
          'themes': 'مواضيع',
          'about': 'حول',
          'privacy_policy': 'سياسة الخصوصية',
          'rate_us': 'قيمنا',
          'share': 'شارك',
          'airport': 'مطار',
          'aquarium': 'حوض السمك',
          'art_gallery': 'صالة عرض فنية',
          'atm': 'صراف آلي',
          'automotive': 'سيارات',
          'bakery': 'مخبز',
          'bank': 'بنك',
          'bar': 'بار',
          'bicycle_store': 'متجر الدراجات',
          'book_store': 'مكتبة',
          'bowling': 'بولينج',
          'bus_station': 'محطة الحافلات',
          'cafeteria': 'كافتيريا',
          'car_wash': 'غسيل السيارات',
          'cemetery': 'مقبرة',
          'church': 'كنيسة',
          'city_hall': 'بلدية',
          'clothing_store': 'متجر ملابس',
          'college_university': 'كلية جامعة',
          'court_house': 'محكمة',
          'dentist': 'طبيب أسنان',
          'doctor': 'طبيب',
          'department': 'قسم',
          'electrician': 'كهربائي',
          'electronic_store': 'متجر إلكترونيات',
          'embassy': 'سفارة',
          'furtniture_store': 'متجر الأثاث',
          'gas_station': 'محطة وقود',
          'gym': 'نادي رياضي',
          'hardware_store': 'محل الأدوات',
          'hospital': 'مستشفى',
          'hotel': 'فندق',
          'jewelry_store': 'متجر مجوهرات',
          'laundry': 'غسيل',
          'lawyer': 'محام',
          'library': 'مكتبة',
          'mosque': 'مسجد',
          'museum': 'متحف',
          'painter': 'رسام',
          'park': 'حديقة',
          'parking': 'موقف سيارات',
          'pharmacy': 'صيدلية',
          'pet_store': 'متجر الحيوان',
          'plumber': 'سباك',
          'police_station': 'مركز ش',
          'post_office': 'مكتب البريد',
          'real_estate': 'عقارات',
          'restaurant': 'مطعم',
          'school': 'مدرسة',
          'shopping_mall': 'مركز تسوق',
          'spa': 'منتجع صحي',
          'stadium': 'استاد',
          'subway_station': 'محطة مترو',
          'taxi_stand': 'محطة سيارات أجرة',
          'travel_agency': 'وكالة سفر',
          'zoo': 'حديقة حيوان',
        },
        // German translations
        'de_DE': {
          'select_language': 'Sprache auswählen',
        },
        // French translations
        'fr_FR': {
          'select_language': 'Choisir la langue',
        },
        // Hindi translations
        'hi_IN': {
          'select_language': 'भाषा चुनें',
        },
        // Spanish translations
        'es_ES': {
          'select_language': 'Seleccionar idioma',
        }
      };
}
